name: Publish daily air quality summary
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  publish-air-quality-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write && read
      pages : write
      id-token : write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #full history

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          pip install requests
          pip install jinja2

      - name: Create html table from data
        env: 
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
        run: |
          python scripts/create-daily-air-quality-html.py
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "New daily air quality summary added" || echo "No new changes to commit"
          git push 

      - name: Setup production branch
        run: |
          if ! git show-ref --verify --quiet refs/heads/production; then 
            git checkout --orphan production
            git rm -rf .

            git pull origin production
            
            mkdir -p content
            touch .nojekyll
            echo "# Production Content" > content/README.md 

            git add .nojekyll content/README.md
            git commit -m "Initialise production branch" || echo "No new changes to commit"
            git push -u origin production
          fi

      - name: Incorporate reusable action
        uses: mo-laurenboon/Test-Repo/.github/actions/fetch_branch_path@main
        with:
          branch: 'main'
          path: 'content/'

      - name: Update production from main
        run: |
          git checkout production
          git checkout main -- content/
          git add content/*.html
          git commit -m "HTML copied from main to production"
          git push -u origin production
      
      - environment:
          name: github-pages
          url : ${{ steps.deployment.outputs.page_url }}

      - name : Checkout
        uses : actions/checkout@v4
        with :
          ref : production

      - name : Setup Pages
        uses : actions/configure-pages@v5

      - name : Upload artifact
        uses : actions/upload-pages-artifact@v3
        with :
          path : 'content'
          retention-days : 0

      - name : Deploy to GitHub Pages
        id : deployment
        uses : actions/deploy-pages@v4
