name: Generate and Deploy
on:
  workflow_run:
    workflows: ["daily air quality summary"]
    types:
      - completed
 # push:
  #  branches: 
  #    - 'main'
 #   paths:
      - 'content/**'
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #full history
      - name: Setup production branch
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'

          if ! git show-ref --verify --quiet refs/heads/production; then 
            git checkout --orphan production
            git rm -rf .

            git pull origin production
            
            mkdir -p content
            touch .nojekyll
            echo "# Production Content" > content/README.md 

            git add .nojekyll content/README.md
            git commit -m "Initialise production branch" || echo "No new changes to commit"
            git push -u origin production
          fi
      - name: Incorporate reusable action
        uses: mo-laurenboon/Test-Repo/.github/actions/fetch_branch_path@main
        with:
          branch: 'main'
          path: 'content/'
      - name: Update production from main
        run: |
          git checkout production
          git checkout main -- content/
          git add content/*.html
          git commit -m "HTML copied from main to production"
          git push -u origin production
